# Generated by Django 3.1.1 on 2020-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500, verbose_name='Имя_Фамилия')),
                ('task', models.TextField(max_length=500, verbose_name='Что такое HTML?')),
                ('tagcss', models.TextField(max_length=500, verbose_name='Что такое CSS?')),
                ('tagulol', models.TextField(max_length=500, verbose_name='Как сделать Ненумерованный список в нумерованном?Написать тегами')),
                ('tagmarginmargin', models.TextField(max_length=500, verbose_name='Какая разница между значениями margin 10px и margin 10px 10px в свойстве margin?')),
                ('tagssilka', models.TextField(max_length=500, verbose_name='Ссылки. Как задать адрес документа, на который следует перейти? Написать тегом')),
                ('tagbackground', models.TextField(max_length=500, verbose_name='Какое свойство задает цвет заднего фона?')),
                ('tagregistr', models.TextField(max_length=500, verbose_name='В каком регистре лучше писать HTML-код?')),
                ('tagclassred', models.TextField(max_length=500, verbose_name='Как задать красный цвет для всех элементов, имеющих класс red?')),
                ('tagtr', models.TextField(max_length=500, verbose_name='Зачем нужнeн тег tr')),
                ('tagmarginpadding', models.TextField(max_length=500, verbose_name='В чем разница между margin и padding?')),
                ('tagdivspan', models.TextField(max_length=500, verbose_name='В чем разница между div и span?')),
                ('tagimage', models.TextField(max_length=500, verbose_name='Как добавить картинку на страницу?написать тегом')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
